---
- hosts: all

  tasks:
#  Used to check if when a host fail in a task, the other tasks continues on the other hosts
#  - name: Checking ping with OS
#    command: "ping -c 2 {{ ansible_nodename }}"

  - name: Information
    debug: 
      msg:
       - "OS distribution [{{ ansible_distribution }}]"
       - "OS version [{{ ansible_distribution_major_version }}]"

  - name: Checking Health
    ping: 
